name: Terraform Lint

on:
  push:
    paths:
    - './.github/workflows/terraform-lint.yaml'
    - './**/*.tf'
    - './*.tf'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: terraform fmt
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: fmt -check -recursive
        tf_actions_version: latest

    - name: terraform validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: validate
        tf_actions_version: latest

