name: Terraform

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: terraform fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: fmt
          tf_actions_version: latest

      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
          tf_actions_version: latest
          args: '-backend-config="access_key=${{ secrets.SPACES_ACCESS_TOKEN }}" -backend-config="secret_key=${{ secrets.SPACES_SECRET_KEY }}" -backend-config="bucket=${{ secrets.SPACES_BUCKET_NAME }}"'

      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: validate
          tf_actions_version: latest
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TF_VAR_name: ${{ secrets.KUBERNETES_CLUSTER_NAME }}
